### PR TITLE
Update uniswap-v3.ts

### LINKED ISSUE #4: Incorrect type definition for `uniswap-v3.txData` return type.
`uniswap-v3.d.ts` has a return type of `{ ..., data: any, ... } | undefined`.  When I look at `uniswap-v3.ts` in my editor, it shows the return type as `{ ..., data: Uint8Array, ...}` (`data` is `Uint8Array` and no undefined returns) but for some reason this got lost in the generated `.d.ts`.

 I suspect the problem is with https://github.com/paulmillr/micro-web3/blob/d493effd71553cd2c57a6dcddc092ed6d67841ea/src/api/uniswap-v3.ts#L168-L173

You aren't assigning a type to `calldatas`, which means it derives its type from the stuff pushed into it, and then you are pushing `any` into it on the following line which sets its type to `any[]`.

### PR DESCRIPTION
**Pull request by MicahZoltu**
Fixes #4 
....maybe.

### CODE REVIEW

**Comment by MicahZoltu** [comment]
I'm sad that CI doesn't tell me what the correct formatting is.  I don't have this repository cloned locally, so I'm not sure how exactly to fix it.

**Comment by paulmillr** [comment]
>I don't have this repository cloned locally

Why?

>so I'm not sure how exactly to fix it.

Clone it locally and run a linter, or use GitHub Codespaces which is 100% cloud.

**Comment by MicahZoltu** [comment]
Because submitting a PR by clicking the edit button in GitHub takes 30 seconds to a couple minutes, especially if I already have the code changes from debugging completed in a copy in my local node_modules for my project.

Cloning the repository into a docker container (for sandboxing) and running a script or doing the same with Codespaces takes many minutes.

**Comment by MicahZoltu** [comment]
Also, figuring out that `npx prettier --write` is the command I need is non trivial as someone who doesn't use prettier.  There are no NPM scripts configured in this project for it.

**Comment by MicahZoltu** [comment]
Note: Command appears to actually be `npx prettier --write src/`.  Whole process took me almost 4 minutes, and that is with your hint on how to use prettier.  😬

**Comment by paulmillr** [comment]
Yeah, lack of command was my mistake. In other repos it's present.

I'm convinced the code quality is massively improved by using prettier. Consistency in all repos for all authors is great.

**Pull request merged**
